version: 2.1
jobs:
  deploy:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run: sh publish_pod_ocean_tokens.sh          
      - run: pod install
      - deploy:
          name: Deploy
          command: fastlane upload_to_diawi

workflows:
  test_release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master