
version: 2.1
executors:
  mac_exe:
    macos:
      xcode: "11.4.1"

commands:
  deploy_app:
    description: "Build the application before tests"
    steps:
      - add_ssh_keys:
        fingerprints:
          - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - run: sh publish_pod_ocean_tokens.sh          
      - run: bundle exec fastlane upload_to_diawi

  config_workspace:
    description: "Install or Restore configurations"
    steps:
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Install Bundle if not exist in cache
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle
      - restore_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install Pods
          command: pod install
      - save_cache:
          key: build-temp-pods-{{ checksum "Podfile.lock" }}
          paths: 
            - Pods/

jobs:
  config-workspace:
    macos:
      xcode: 11.4.1 # Specify the Xcode version to use
    steps:
      - checkout
      - config_workspace
      - deploy_app

workflows:
  version: 2.1
  commit:
    jobs:
      - config-workspace:
          filters:
            branches:
              only: master
